on:
  workflow_dispatch:

permissions: read-all

env:
  project-directory: ./
name: Deploy website
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: philnorcross.com
        username: green
        port: 21
        protocol: ftps
        local-dir: greenorg/docs/
        server-dir: /
        state-name: .deployHistory
        dry-run: false
        log-level: standard
        security: loose
        password: ${{ secrets.philftp }}
        

